# Generated by Django 5.0.6 on 2024-10-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entries",
            name="entry",
            field=models.TextField(null=True),
        ),
    ]
