# Generated by Django 5.0.6 on 2024-10-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0002_entries_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entries",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
